pipeline {
    agent {
        
            //image 'maven:3.8.6-jdk11' // Specify the Docker image with Maven and JDK
            docker { image 'maven:3.8.1-adoptopenjdk-11' }
            //label 'docker-agent' // Optional: specify a label if needed
        
    }

    stages {
        stage('Build and Package') {
            steps {
                script {
                    // Run Maven commands inside the Docker container
                    sh 'mvn clean install'
                    sh 'mvn package'
                }
            }
        }
    }

    post {
        always {
            // Archive the build artifacts
            archiveArtifacts artifacts: '**/target/*.jar', allowEmptyArchive: true
        }

        success {
            echo 'Build and packaging succeeded!'
        }

        failure {
            echo 'Build or packaging failed.'
        }
    }
}