pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn compile'
      }
      steps {
        sh 'mvn package'
      }
      steps {
       sh 'java -cp target/hello-world-maven-1.0-SNAPSHOT.jar com.example.Main'

      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
