pipeline {
  agent none
  stages {
    stage('Build') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
        steps {
                script {
                    // Execute Maven install and package commands
                    sh "mvn clean install"
                }
        }
      }
    }

        stage('Package') {
            steps {
                script {
                    // Package the application into a JAR file
                    sh "mvn package"
                }
            }
        }
      
      stage('Maven target'){
        steps {
       sh 'java -cp target/hello-world-maven-1.0-SNAPSHOT.jar com.example.Main'

      }
      
      }
      
      
  }
}
